### ISSUE TITLE
[SIA] keepalived.conf 文件的权限错误

### ISSUE THREAD

**Issue by mx-zheng** [nocsysmars/mars_allin_one#22]
该文件当前权限为：
![image](https://user-images.githubusercontent.com/22835075/77504474-6adbd700-6e9b-11ea-93ac-c400b0ef5cb4.png)

docker-compose up 启动后，keepalived 容器报错且无法启动：
![image](https://user-images.githubusercontent.com/22835075/77504571-ac6c8200-6e9b-11ea-9582-cdc7108a0368.png)

解决：
chmod 644 keepalived.conf

**Comment by macauleycheng** [comment]
done
